title: "Wladimir Gramacho"
description: ""
url: "https://wggramacho.github.io"
baseurl: ""

header_pages:
  - index.md
  - publications.md
  - cv.md
  - contact.md

theme: minima

plugins:
  - jekyll-sitemap
